name: redbuus
favicon: null
layout_spectrum: 0.24787
typography_spectrum: 0.75554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3174ac'
    - '#eff2f7'
    - '#60410d'
    - '#bbc7d6'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
